name: 'Yarn Build with Cache'
description: 'Run yarn build using yarn cache'

inputs:
  ref:
    description: 'The Git ref to checkout'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache Hardhat compilers
      # Hardhat downloads solc into ~/.cache/hardhat-nodejs
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/hardhat-nodejs
        key: hardhat-solc-${{ runner.os }}-${{ hashFiles('**/hardhat.config.*') }}

    - name: Cache Starknet contract release artifacts
      # @hyperlane-xyz/starknet-core downloads precompiled contracts during build.
      # Cache them to reduce network flakiness and speed up repeated builds.
      uses: actions/cache@v4
      with:
        path: |
          starknet/release
        key: starknet-release-${{ runner.os }}-${{ hashFiles('starknet/scripts/fetch-contracts-release.sh') }}

    - name: yarn-cache
      id: yarn-cache
      uses: ./.github/actions/yarn-cache

    # Typically, the cache will be hit, but if there's a network error when
    # restoring the cache, let's run the install step ourselves.
    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install
        CHANGES=$(git status -s --ignore-submodules | grep -v "results.sarif" || true)
        if [[ ! -z $CHANGES ]]; then
          echo "Changes found: $CHANGES"
          git diff
          exit 1
        fi

    - name: Build
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: yarn build
